### ISSUE TITLE
SMTP url with special chars not possible

### ISSUE THREAD

**Issue by John-H-Smith** [kromitgmbh/titra#156]
While trying to use 'forgot password', this error occurred (url censored):
```
Exception while invoking method 'forgotPassword' TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: smtps://noreply@my-domain.com:my-password-with-special-chars@host.my-server-host.com:587
    at new NodeError (internal/errors.js:322:7)
    at onParseError (internal/url.js:270:9)
    at new URL (internal/url.js:346:5)
    at getTransport (packages/email/email.js:126:24)
    at packages/email/email.js:316:23
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at Object.Email.send (packages/email/email.js:250:18)
    at AccountsServer.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:540:9)
    at MethodInvocation.forgotPassword (packages/accounts-password/password_server.js:385:12)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1902:12)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
    at packages/ddp-server/livedata_server.js:791:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43
```
As you can see, my mail user is the email address itself, in the example above `noreply@my-domain.com`.
The password uses some special characters.

**Comment by faburem** [comment]
How are you supplying the SMTP URL?
If you are using Docker compose you might need to wrap the whole environment variable in double quotes like so:
```
environment:
   - "MAIL_URL=smtps://apikey:password@smtp.sendgrid.net:465"
```
(this is an example of how we are using sendgrid to send emails in our own production environment)

**Comment by John-H-Smith** [comment]
Thanks @faburem for the answer.
Yeah, I'm using docker-compose.
I just tried wrapping the whole variable into double quotes, but the issue is the same.
I assume, it might be because of the @ within the mail user

**Comment by faburem** [comment]
maybe you can try url encoding the username i.e. replacing @ with %40:
`no-reply%40my-domain.com`

**Comment by faburem** [comment]
Hi,
yes I can confirm it is working fine with sendgrid:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/11456790/220059118-503e249c-c22d-4f26-84aa-be13c901b706.png">

**Comment by John-H-Smith** [comment]
Okay, so the user for your sendgrid is also the email address (with @)?
If yeah, can you confirm that you use special characters in your password to verify those are not the problem?

**Comment by faburem** [comment]
the user for the sendgrid smtp service is apikey,
the password is full of special characters since it is automatically created (i.e. an apikey)

**Comment by John-H-Smith** [comment]
Alright, so have you ever tried using a smtp user with a '@' in it?
EDIT:
I just saw the mail comes from meteor - I will address this issue there. Thanks for your help!
