### ISSUE TITLE
Random server shutdowns (Exception in changedobserveChanges callback)

### ISSUE THREAD

**Issue by readtedium** [kromitgmbh/titra#211]
Hi there, just reaching out because I’m occasionally running into issues where the server is offline, requiring a restart. (Data appears to be unaffected, but I could see this a problem if I’m trying to track something in real-time.)

Looking for potential issues, I spotted this Meteor.js error in my logs:

```
2024-06-12 02:25:48
Exception in changedobserveChanges callback: TypeError: Cannot read property '7cmJBQm2fiEsmWvEQ' of undefined
2024-06-12 02:25:48
at changed (imports/api/projects/server/publications.js:188:29)
2024-06-12 02:25:48
at runWithEnvironment (packages/meteor.js:1486:24)
2024-06-12 02:25:48
at packages/meteor.js:1499:14
2024-06-12 02:25:48
at packages/mongo/observe_multiplex.js:178:30
2024-06-12 02:25:48
at Array.forEach (<anonymous>)
2024-06-12 02:25:48
at Function._.each._.forEach (packages/underscore.js:139:11)
2024-06-12 02:25:48
at Object.task (packages/mongo/observe_multiplex.js:172:9)
2024-06-12 02:25:48
at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
2024-06-12 02:25:48
at packages/meteor.js:1003:12
```

Any idea what might be causing this?

**Comment by faburem** [comment]
should be fixed in titra version 0.97.3!

**Comment by readtedium** [comment]
Sounds good—I will try it and report back if I see any issues. Thank you for your great work as always!

**Comment by readtedium** [comment]
Seems to be running much better; closing for now. Thank you!
