### ISSUE TITLE
Error when saving times after update

### ISSUE THREAD

**Issue by the-markus** [kromitgmbh/titra#213]
Titra was updated to the newest version (Titra version: 0.99.8, MongoDB server version: 5.0.28) and we now get the following error when trying to save/track time:

```
Exception while invoking method 'insertTimeCard' Error: insert +  is not available on the server. Please use insertAsync() instead.
    at Object.ret.<computed> [as insert] (packages/mongo/remote_collection_driver.js:52:15)
    at Collection._insert (packages/mongo/collection.js:732:35)
    at Collection.insert (packages/mongo/collection.js:755:17)
    at MethodInvocation.methodOptions.run (imports/utils/server_method_helpers.js:644:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by the-markus** [comment]
Thank you! It works!
