### ISSUE TITLE
Week Track time view not working properly since upgrading to Version 0.99.19

### ISSUE THREAD

**Issue by CaptainPackers** [kromitgmbh/titra#222]
I used to use the Week "Track time" view regularly and it worked flawlessly until I upgraded to Version 0.99.19.

1. The Next week button in the upper right no longer advances the data viewed to the next week.
2. The summary column shows the correct number of hours for the week, but the individual days do not display properly.

![Capture](https://github.com/user-attachments/assets/5612d8c9-d2e6-4e09-90b1-270a325b8aab)

Here is the pertinent app/system information. Note that Titra is running on an Ubuntu server, and the client is a Windows system.

![Capture2](https://github.com/user-attachments/assets/f11eb31b-6fb4-45db-9bfa-5d2e20340f61)

**Server:** Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-48-generic x86_64)

**Client:**
Processor	11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz   1.50 GHz
Installed RAM	8.00 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Education
Version	22H2
OS build	19045.5131
Experience	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by faburem** [comment]
Can you please try it with the latest version 0.99.21? While I was not able to reproduce the problem on my side, a similar issue was reported which might also fix this one. If not, are there any errors in the logs you can share?

Thanks!

**Comment by faburem** [comment]
Maybe you can at least share the browser developer console if there are any errors displayed there?

**Comment by faburem** [comment]
Hi, can you please try again with version 0.99.23?

Thanks,
Fabian

**Comment by CaptainPackers** [comment]
Running 0.99.26 now, still not change. The week view won't advance forward and the project/task summaries show the total for the week, but no values for individual days.

Regards,
Captain
--
Sent with Tutanota, enjoy secure & ad-free emails.



Dec 2, 2024, 3:29 AM by ***@***.***:

**Comment by CaptainPackers** [comment]
Here's the console messages. The "Unauthorized" parts look bad. Could it be related to not using SSL? I am on a private network in my home office so I didn't want to do the whole port forwarding and certificate thing.

Thanks.

Regards,
Captain Packers---
:8080/api/boards/rvLH4HJg9WQGmfGDa/lists/nPESXyKbooc9omaW9/cards:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
2commons.js:2 Uncaught (in promise) y: {}
    at y.fromAny (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/commons.js:2:2969702)
    at S._handleResponsePromise (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/commons.js:2:960588)
    at S._handleDispatchResponse (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/commons.js:2:960356)
    at S._handleMessage (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/commons.js:2:960072)
    at _listener (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/commons.js:2:959892)
:8080/api/boards/rvLH4HJg9WQGmfGDa/lists/nPESXyKbooc9omaW9/cards:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
:8080/api/boards/rvLH4HJg9WQGmfGDa/lists/nPESXyKbooc9omaW9/cards:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
:8080/api/boards/rvLH4HJg9WQGmfGDa/lists/nPESXyKbooc9omaW9/cards:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
:3000/tracktime/gNDdYnnwgtPMdFQzT:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
:3000/tracktime/gNDdYnnwgtPMdFQzT:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
f68185cc109e341171c313ce15afefad8a08af25.js?meteor_js_resource=true:140 The specified value "" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
update @ f68185cc109e341171c313ce15afefad8a08af25.js?meteor_js_resource=true:140
f68185cc109e341171c313ce15afefad8a08af25.js?meteor_js_resource=true:140 The specified value "Invalid Date" does not conform to the required format, "yyyy-MM-dd".
update @ f68185cc109e341171c313ce15afefad8a08af25.js?meteor_js_resource=true:140
f68185cc109e341171c313ce15afefad8a08af25.js?meteor_js_resource=true:140 The specified value "Invalid Date" does not conform to the required format, "yyyy-MM-dd".
update @ f68185cc109e341171c313ce15afefad8a08af25.js?meteor_js_resource=true:140
[Violation] Forced reflow while executing JavaScript took 36ms
Regards,
Donald Lund
--
Sent with Tutanota, enjoy secure & ad-free emails.



Dec 11, 2024, 7:04 AM by ***@***.***:

**Comment by faburem** [comment]
I might have an idea - can you maybe confirm that you are using the week view as default time tracking view? i.e. you are directed there directly if you click on Track?

**Comment by faburem** [comment]
closing due to inactivity
